language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn test
after_success:
  - yarn add travis-deploy-once@4 semantic-release@11
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  only:
    - master
